

# This file should contain everything to configure the workflow on 
# a global scale. In case of sample based data, it should be complemented by 
# a samples.tsv file that contains one row per sample.

# general parameters for run
sampletable: "samples.tsv"
negcontroltable: "negcontrols.tsv"
metadata: "meta.tsv"

threads: 32


# dada2 filter and trim
truncQ: 12
truncLen:
  - 280
  - 250
trimLeft: 0
trimRight: 0
maxLen: Inf
minLen: 100
maxN: 0
minQ: 0
maxEE:
  - 2
  - 2

# dada2 learn error rates
learn_nbases: 100e6

# dada2 merge pairs
minOverlap: 50
maxMismatch: 0

# dada2 remove chimeras
minSampleFraction: 0.9
ignoreNNegatives: 1
minFoldParentOverAbundance: 1.5
allowOneOf: FALSE
minOneOffParentDistance: 4
maxShift: 16
chimera_method: "consensus"

# qc parameters
negctrl_prop: 0.5 # proportion of negative control reads to be subtracted from sample reads vectors
max_length_variation: 50 # bps can a sequence be longer or shorter than the mode sequence length
low_abundance_perc: 0.0001 # min percentage of total_reads in an ASV


# can be downloaded from https://benlangmead.github.io/aws-indexes/k2
kraken_dbs: 
  minikraken2: "taxonomy/minikraken2_v2_8GB_201904_UPDATE/"
  greengenes: "taxonomy/16S_Greengenes_k2db"
  # rdp: "taxonomy/16S_RDP11.5_20200326"
  # silva: "taxonomy/16S_Silva132_20200326"

# According to this issue:
# https://github.com/DerrickWood/kraken2/issues/167  
# For general purposes, 0.05 or 0.1 for general purposes.
# If the classification of ASVs / OTUs of reads < 10 is important, then use
# something higher, e.g. 0.5 
confidence: 0.01

# phyloseq 
# any of c("bray", "fJaccard", "euclidean",
  # "hellinger", "mahalanobis", "manhattan", "bhjattacharyya", "canberra",
  # "chord", "unifrac", "w_unifrac", "w_unifrac_norm")
beta: "bray"